name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '^1.7']
        julia-arch: [x64]
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: run tests
        run: julia --color=yes .ci/ci.jl
        continue-on-error: ${{ matrix.version == 'nightly' }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,lib/MadDiffCore/src,lib/MadDiffSpecialFunctions,lib/MadDiffModels/src,lib/MadDiffMOI/src
      - uses: codecov/codecov-action@v1 
        with:
          file: lcov.info
